### ISSUE TITLE
Snapshot contents

### ISSUE THREAD

**Issue by evancaldwell** [olivierlangelaar/firebase-storage-upload#9]
First off, thanks for putting this together, I had been looking for something and about to write my own. I set a `success` listener in the element containing `firebase-storage-upload` and it get's called properly but the `snapshot` doesn't seem to have the same data as the snapshot coming from firebase. Specifically I'm looking for the `downloadURL` property. I set a breakpoint on line 144 and `self.uploadTask.snapshot.downloadURL` does contain the proper string so either I don't know the path to `downloadURL` within the snapshot in the success callback or the data of the Firebase snapshot isn't being passed through.

**Comment by olivierlangelaar** [comment]
You're right, `snapshot` is empty, I'll look into it

**Comment by olivierlangelaar** [comment]
https://github.com/olivierlangelaar/firebase-storage-upload/pull/10

**Comment by evancaldwell** [comment]
I did find a workaround. Within the success callback `snapshot.target.uploadTask.snapshot.downloadURL` contains the info I was looking for but it seems like you probably want to be able to access `snapshot` without having to use `.target.uploadTask`.

**Comment by olivierlangelaar** [comment]
the snapshot is in the uploadTask property on the element,
Latest version also returns it on-success. If you need anything else let me know
